version: "3"
services:
  user-db:
    container_name: user-db
    image: postgres:12.3
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    container_name: grafana
    depends_on:
      - prometheus
      - prometheus-pushgateway
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    container_name: user-prometheus
  prometheus-pushgateway:
    image: prom/pushgateway
    container_name: user-pushgateway
    expose:
      - 9091
    ports:
      - 9091:9091
  users-api:
    container_name: users-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
volumes:
  db_data:
